### ISSUE TITLE
Compatibility with ESP-01

### ISSUE THREAD

**Issue by mrx23dot** [rumpeltux/esp-stlink#13]
ESP-01 only has pins:  GPIO0, GPIO2  available

comm: GPIO1 (TX), GPIO3 (RX)

**Comment by mrx23dot** [comment]
https://github.com/rumpeltux/esp-stlink/pull/14

**Comment by rumpeltux** [comment]
I left a hint in the README at 94ea6a4. For the next stable release, we can update the pin names according to your original pull request (I don’t have a build-environment ready right now…).
