### ISSUE TITLE
Not working on the WEMOS D1 Mini ESP8266

### ISSUE THREAD

**Issue by Psyden57** [rumpeltux/esp-stlink#19]
I'm trying to flash onto an STM8103f3p6, but i keep getting this error:

```
psyden5757@PsyBook:~/Desktop/STM8FLASH/example/stm8s-sdcc-examples$ stm8flash -c espstlink -d /dev/ttyUSB0 -p stm8s103f3 -w led.ihx
Determine FLASH area
Unexpected data: c4

Unexpected data: c4

Error communicating with MCU. Please check your SWIM connection.
```

help?

**Comment by rumpeltux** [comment]
When I saw similar messages in my previous attempts typical causes were:

* resistor of improper value / not properly connected
* unstable power supply (e.g. USB hub), try adding an additional external 3.3V/5V power source to your setup
* cabling issues (noise in cables / cables touching stuff / cables acting as antennas)

Good luck.
