### ISSUE TITLE
Debugging?

### ISSUE THREAD

**Issue by spth** [rumpeltux/esp-stlink#4]
So far, this hardware is supported by stm8flash, allowing us to read and write memory on the STM8 without having to rely on the ST-Link with its non-free firmware.

However, there are patches to OpenOCD and GDB to also allow on-target debugging via the ST-Link. Would on-target debugging work witht he ESP-STLINK? How much work would it be to add support to the OpenOCD patches?

Philipp

**Comment by rumpeltux** [comment]
I don’t know any of the OpenOCD details, but given that debugging is solely implemented by modifying memory mapped registers, I’d say it should be fairly easy. Essentially just the transport layer that communicates with stlink has to be replaced to talk to esp-stlink instead.
